language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3 # see https://docs.travis-ci.com/user/osx-ci-environment/


install: true

script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew test
