language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
#  - os: osx
#    osx_image: xcode8.3
install: true
script:
- "./gradlew clean"
- "./gradlew build"
- "./gradlew test"
- "./gradlew jar"
- if [ "$TRAVIS_BRANCH" = release/* ]; then ./gradlew publish; fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
   - "build/libs/*"
  skip_cleanup: true
  on:
    tags: true
